### ISSUE TITLE
Bug in on_attributes_changed in the python agent

### ISSUE THREAD

**Issue by braunale** [livekit-examples/realtime-playground#15]
Hey, 

I found a bug in the python agent (playground_agent.py). In line 121 it should be !== instead of ==. 
For reference you could check the according line in the node agent (Line 127 in playground_agent.ts) in which the if statement is implemented correctly. This causes a bug when using the python agent that changes to the config do not apply instantly but only on the next dialog turn, since with the current implementation, all update on the local participant are skipped while changes on the remot participant are handled and it should be the other way arround. 

Python Agent:
```
def on_attributes_changed(
        changed_attributes: dict[str, str], changed_participant: rtc.Participant
    ):
        if changed_participant == participant:
            return
```

Node Agent:
```
ctx.room.on(
    "participantAttributesChanged",
    (
      changedAttributes: Record<string, string>,
      changedParticipant: Participant,
    ) => {
      if (changedParticipant !== participant) {
        return;
      }
```

**Comment by davidzhao** [comment]
thanks for finding this. would you like to open a PR? 

no worries if not, we'll get to it!
