### ISSUE TITLE
fix useKrispNoiseFilter import error

### ISSUE THREAD

**Issue by gianpaj** [livekit-examples/realtime-playground#4]
https://github.com/livekit/components-js/pull/991

**Comment by sunilvb** [comment]
+1
getting the following error in Web Frontend:

Attempted import error: 'useKrispNoiseFilter' is not exported from '@livekit/components-react' (imported as 'useKrispNoiseFilter').

Import trace for requested module:
./src/components/session-controls.tsx
./src/components/chat.tsx
./src/components/room-component.tsx

**Comment by lukasIO** [comment]
Hey, thanks for the report, this is because we were forced to change export paths for the krisp hook, you can import it via `@livekit/components-react/krisp` in newer versions.
